kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scalog-operator
  namespace: scalog
subjects:
- kind: ServiceAccount
  name: scalog-operator
roleRef:
  kind: Role
  name: scalog-operator
  apiGroup: rbac.authorization.k8s.io
